version: '3.9'

services:
  server:
    build:
      context: ./server
    container_name: node-server
    networks:
      - client-server
    ports:
      - 5000:5000
    volumes:
      - ./server:/server
      - /app/node_modules
  client:
    build:
      context: ./client
    container_name: react-client
    networks:
      - client-server
    ports:
      - 3000:3000
    
networks:
  client-server:
    driver: bridge
